// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/peer/v1/peer.proto

package peerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Envelope is one control-channel message. Each WebRTC data-channel send carries
// exactly one Envelope (SCTP preserves message boundaries; no length prefix needed).
type Envelope struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*Envelope_Handshake
	//	*Envelope_Ping
	//	*Envelope_Pong
	Body          isEnvelope_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_peer_v1_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_v1_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_peer_v1_peer_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *Envelope) GetBody() isEnvelope_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Envelope) GetHandshake() *Handshake {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Handshake); ok {
			return x.Handshake
		}
	}
	return nil
}

func (x *Envelope) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Envelope) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

type isEnvelope_Body interface {
	isEnvelope_Body()
}

type Envelope_Handshake struct {
	Handshake *Handshake `protobuf:"bytes,2,opt,name=handshake,proto3,oneof"`
}

type Envelope_Ping struct {
	Ping *Ping `protobuf:"bytes,3,opt,name=ping,proto3,oneof"`
}

type Envelope_Pong struct {
	Pong *Pong `protobuf:"bytes,4,opt,name=pong,proto3,oneof"`
}

func (*Envelope_Handshake) isEnvelope_Body() {}

func (*Envelope_Ping) isEnvelope_Body() {}

func (*Envelope_Pong) isEnvelope_Body() {}

// Handshake is exchanged once when the control channel opens.
type Handshake struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Capabilities    []string               `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Handshake) Reset() {
	*x = Handshake{}
	mi := &file_proto_peer_v1_peer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handshake) ProtoMessage() {}

func (x *Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_v1_peer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handshake.ProtoReflect.Descriptor instead.
func (*Handshake) Descriptor() ([]byte, []int) {
	return file_proto_peer_v1_peer_proto_rawDescGZIP(), []int{1}
}

func (x *Handshake) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Handshake) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_proto_peer_v1_peer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_v1_peer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_proto_peer_v1_peer_proto_rawDescGZIP(), []int{2}
}

func (x *Ping) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_proto_peer_v1_peer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_v1_peer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_proto_peer_v1_peer_proto_rawDescGZIP(), []int{3}
}

func (x *Pong) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

var File_proto_peer_v1_peer_proto protoreflect.FileDescriptor

const file_proto_peer_v1_peer_proto_rawDesc = "" +
	"\n" +
	"\x18proto/peer/v1/peer.proto\x12\apeer.v1\"\xaf\x01\n" +
	"\bEnvelope\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x122\n" +
	"\thandshake\x18\x02 \x01(\v2\x12.peer.v1.HandshakeH\x00R\thandshake\x12#\n" +
	"\x04ping\x18\x03 \x01(\v2\r.peer.v1.PingH\x00R\x04ping\x12#\n" +
	"\x04pong\x18\x04 \x01(\v2\r.peer.v1.PongH\x00R\x04pongB\x06\n" +
	"\x04body\"Z\n" +
	"\tHandshake\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\"\x1c\n" +
	"\x04Ping\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce\"\x1c\n" +
	"\x04Pong\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonceB5Z3github.com/squall-chua/p2p-hls/proto/peer/v1;peerv1b\x06proto3"

var (
	file_proto_peer_v1_peer_proto_rawDescOnce sync.Once
	file_proto_peer_v1_peer_proto_rawDescData []byte
)

func file_proto_peer_v1_peer_proto_rawDescGZIP() []byte {
	file_proto_peer_v1_peer_proto_rawDescOnce.Do(func() {
		file_proto_peer_v1_peer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_peer_v1_peer_proto_rawDesc), len(file_proto_peer_v1_peer_proto_rawDesc)))
	})
	return file_proto_peer_v1_peer_proto_rawDescData
}

var file_proto_peer_v1_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_peer_v1_peer_proto_goTypes = []any{
	(*Envelope)(nil),  // 0: peer.v1.Envelope
	(*Handshake)(nil), // 1: peer.v1.Handshake
	(*Ping)(nil),      // 2: peer.v1.Ping
	(*Pong)(nil),      // 3: peer.v1.Pong
}
var file_proto_peer_v1_peer_proto_depIdxs = []int32{
	1, // 0: peer.v1.Envelope.handshake:type_name -> peer.v1.Handshake
	2, // 1: peer.v1.Envelope.ping:type_name -> peer.v1.Ping
	3, // 2: peer.v1.Envelope.pong:type_name -> peer.v1.Pong
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_peer_v1_peer_proto_init() }
func file_proto_peer_v1_peer_proto_init() {
	if File_proto_peer_v1_peer_proto != nil {
		return
	}
	file_proto_peer_v1_peer_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Handshake)(nil),
		(*Envelope_Ping)(nil),
		(*Envelope_Pong)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_peer_v1_peer_proto_rawDesc), len(file_proto_peer_v1_peer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_peer_v1_peer_proto_goTypes,
		DependencyIndexes: file_proto_peer_v1_peer_proto_depIdxs,
		MessageInfos:      file_proto_peer_v1_peer_proto_msgTypes,
	}.Build()
	File_proto_peer_v1_peer_proto = out.File
	file_proto_peer_v1_peer_proto_goTypes = nil
	file_proto_peer_v1_peer_proto_depIdxs = nil
}
