// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/peer/v1/peer.proto

package peerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error_Status int32

const (
	Error_STATUS_UNSPECIFIED Error_Status = 0
	Error_DENIED             Error_Status = 1
	Error_NOT_FOUND          Error_Status = 2
	Error_UNAVAILABLE        Error_Status = 3
	Error_INTERNAL           Error_Status = 4
	Error_BUSY               Error_Status = 5
)

// Enum value maps for Error_Status.
var (
	Error_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "DENIED",
		2: "NOT_FOUND",
		3: "UNAVAILABLE",
		4: "INTERNAL",
		5: "BUSY",
	}
	Error_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"DENIED":             1,
		"NOT_FOUND":          2,
		"UNAVAILABLE":        3,
		"INTERNAL":           4,
		"BUSY":               5,
	}
)

func (x Error_Status) Enum() *Error_Status {
	p := new(Error_Status)
	*p = x
	return p
}

func (x Error_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Error_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_peer_v1_peer_proto_enumTypes[0].Descriptor()
}

func (Error_Status) Type() protoreflect.EnumType {
	return &file_proto_peer_v1_peer_proto_enumTypes[0]
}

func (x Error_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Error_Status.Descriptor instead.
func (Error_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_peer_v1_peer_proto_rawDescGZIP(), []int{12, 0}
}

// Envelope is one control-channel message. Each WebRTC data-channel send carries
// exactly one Envelope (SCTP preserves message boundaries; no length prefix needed).
type Envelope struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*Envelope_Handshake
	//	*Envelope_Ping
	//	*Envelope_Pong
	//	*Envelope_Browse
	//	*Envelope_Catalog
	//	*Envelope_GetMetadata
	//	*Envelope_TitleMeta
	//	*Envelope_RequestAccess
	//	*Envelope_AccessGranted
	//	*Envelope_Ack
	//	*Envelope_Error
	//	*Envelope_GetPlaylist
	//	*Envelope_Playlist_
	//	*Envelope_GetSegment
	//	*Envelope_Download
	//	*Envelope_JoinParty
	//	*Envelope_PartyWelcome
	//	*Envelope_PartyInvite
	//	*Envelope_PartyState
	//	*Envelope_PartyAudience
	//	*Envelope_LeaveParty
	//	*Envelope_PartyEnded
	//	*Envelope_SwarmHave
	//	*Envelope_GetSwarmSegment
	Body          isEnvelope_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_peer_v1_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_v1_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_peer_v1_peer_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *Envelope) GetBody() isEnvelope_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Envelope) GetHandshake() *Handshake {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Handshake); ok {
			return x.Handshake
		}
	}
	return nil
}

func (x *Envelope) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Envelope) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *Envelope) GetBrowse() *Browse {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Browse); ok {
			return x.Browse
		}
	}
	return nil
}

func (x *Envelope) GetCatalog() *Catalog {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Catalog); ok {
			return x.Catalog
		}
	}
	return nil
}

func (x *Envelope) GetGetMetadata() *GetMetadata {
	if x != nil {
		if x, ok := x.Body.(*Envelope_GetMetadata); ok {
			return x.GetMetadata
		}
	}
	return nil
}

func (x *Envelope) GetTitleMeta() *TitleMeta {
	if x != nil {
		if x, ok := x.Body.(*Envelope_TitleMeta); ok {
			return x.TitleMeta
		}
	}
	return nil
}

func (x *Envelope) GetRequestAccess() *RequestAccess {
	if x != nil {
		if x, ok := x.Body.(*Envelope_RequestAccess); ok {
			return x.RequestAccess
		}
	}
	return nil
}

func (x *Envelope) GetAccessGranted() *AccessGranted {
	if x != nil {
		if x, ok := x.Body.(*Envelope_AccessGranted); ok {
			return x.AccessGranted
		}
	}
	return nil
}

func (x *Envelope) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *Envelope) GetError() *Error {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Envelope) GetGetPlaylist() *GetPlaylist {
	if x != nil {
		if x, ok := x.Body.(*Envelope_GetPlaylist); ok {
			return x.GetPlaylist
		}
	}
	return nil
}

func (x *Envelope) GetPlaylist_() *Playlist {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Playlist_); ok {
			return x.Playlist_
		}
	}
	return nil
}

func (x *Envelope) GetGetSegment() *GetSegment {
	if x != nil {
		if x, ok := x.Body.(*Envelope_GetSegment); ok {
			return x.GetSegment
		}
	}
	return nil
}

func (x *Envelope) GetDownload() *Download {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Download); ok {
			return x.Download
		}
	}
	return nil
}

func (x *Envelope) GetJoinParty() *JoinParty {
	if x != nil {
		if x, ok := x.Body.(*Envelope_JoinParty); ok {
			return x.JoinParty
		}
	}
	return nil
}

func (x *Envelope) GetPartyWelcome() *PartyWelcome {
	if x != nil {
		if x, ok := x.Body.(*Envelope_PartyWelcome); ok {
			return x.PartyWelcome
		}
	}
	return nil
}

func (x *Envelope) GetPartyInvite() *PartyInvite {
	if x != nil {
		if x, ok := x.Body.(*Envelope_PartyInvite); ok {
			return x.PartyInvite
		}
	}
	return nil
}

func (x *Envelope) GetPartyState() *PartyState {
	if x != nil {
		if x, ok := x.Body.(*Envelope_PartyState); ok {
			return x.PartyState
		}
	}
	return nil
}

func (x *Envelope) GetPartyAudience() *PartyAudience {
	if x != nil {
		if x, ok := x.Body.(*Envelope_PartyAudience); ok {
			return x.PartyAudience
		}
	}
	return nil
}

func (x *Envelope) GetLeaveParty() *LeaveParty {
	if x != nil {
		if x, ok := x.Body.(*Envelope_LeaveParty); ok {
			return x.LeaveParty
		}
	}
	return nil
}

func (x *Envelope) GetPartyEnded() *PartyEnded {
	if x != nil {
		if x, ok := x.Body.(*Envelope_PartyEnded); ok {
			return x.PartyEnded
		}
	}
	return nil
}

func (x *Envelope) GetSwarmHave() *SwarmHave {
	if x != nil {
		if x, ok := x.Body.(*Envelope_SwarmHave); ok {
			return x.SwarmHave
		}
	}
	return nil
}

func (x *Envelope) GetGetSwarmSegment() *GetSwarmSegment {
	if x != nil {
		if x, ok := x.Body.(*Envelope_GetSwarmSegment); ok {
			return x.GetSwarmSegment
		}
	}
	return nil
}

type isEnvelope_Body interface {
	isEnvelope_Body()
}

type Envelope_Handshake struct {
	Handshake *Handshake `protobuf:"bytes,2,opt,name=handshake,proto3,oneof"`
}

type Envelope_Ping struct {
	Ping *Ping `protobuf:"bytes,3,opt,name=ping,proto3,oneof"`
}

type Envelope_Pong struct {
	Pong *Pong `protobuf:"bytes,4,opt,name=pong,proto3,oneof"`
}

type Envelope_Browse struct {
	Browse *Browse `protobuf:"bytes,5,opt,name=browse,proto3,oneof"`
}

type Envelope_Catalog struct {
	Catalog *Catalog `protobuf:"bytes,6,opt,name=catalog,proto3,oneof"`
}

type Envelope_GetMetadata struct {
	GetMetadata *GetMetadata `protobuf:"bytes,7,opt,name=get_metadata,json=getMetadata,proto3,oneof"`
}

type Envelope_TitleMeta struct {
	TitleMeta *TitleMeta `protobuf:"bytes,8,opt,name=title_meta,json=titleMeta,proto3,oneof"`
}

type Envelope_RequestAccess struct {
	RequestAccess *RequestAccess `protobuf:"bytes,9,opt,name=request_access,json=requestAccess,proto3,oneof"`
}

type Envelope_AccessGranted struct {
	AccessGranted *AccessGranted `protobuf:"bytes,10,opt,name=access_granted,json=accessGranted,proto3,oneof"`
}

type Envelope_Ack struct {
	Ack *Ack `protobuf:"bytes,11,opt,name=ack,proto3,oneof"`
}

type Envelope_Error struct {
	Error *Error `protobuf:"bytes,12,opt,name=error,proto3,oneof"`
}

type Envelope_GetPlaylist struct {
	GetPlaylist *GetPlaylist `protobuf:"bytes,13,opt,name=get_playlist,json=getPlaylist,proto3,oneof"`
}

type Envelope_Playlist_ struct {
	Playlist_ *Playlist `protobuf:"bytes,14,opt,name=playlist,proto3,oneof"`
}

type Envelope_GetSegment struct {
	GetSegment *GetSegment `protobuf:"bytes,15,opt,name=get_segment,json=getSegment,proto3,oneof"`
}

type Envelope_Download struct {
	Download *Download `protobuf:"bytes,16,opt,name=download,proto3,oneof"`
}

type Envelope_JoinParty struct {
	JoinParty *JoinParty `protobuf:"bytes,17,opt,name=join_party,json=joinParty,proto3,oneof"`
}

type Envelope_PartyWelcome struct {
	PartyWelcome *PartyWelcome `protobuf:"bytes,18,opt,name=party_welcome,json=partyWelcome,proto3,oneof"`
}

type Envelope_PartyInvite struct {
	PartyInvite *PartyInvite `protobuf:"bytes,19,opt,name=party_invite,json=partyInvite,proto3,oneof"`
}

type Envelope_PartyState struct {
	PartyState *PartyState `protobuf:"bytes,20,opt,name=party_state,json=partyState,proto3,oneof"`
}

type Envelope_PartyAudience struct {
	PartyAudience *PartyAudience `protobuf:"bytes,21,opt,name=party_audience,json=partyAudience,proto3,oneof"`
}

type Envelope_LeaveParty struct {
	LeaveParty *LeaveParty `protobuf:"bytes,22,opt,name=leave_party,json=leaveParty,proto3,oneof"`
}

type Envelope_PartyEnded struct {
	PartyEnded *PartyEnded `protobuf:"bytes,23,opt,name=party_ended,json=partyEnded,proto3,oneof"`
}

type Envelope_SwarmHave struct {
	SwarmHave *SwarmHave `protobuf:"bytes,24,opt,name=swarm_have,json=swarmHave,proto3,oneof"`
}

type Envelope_GetSwarmSegment struct {
	GetSwarmSegment *GetSwarmSegment `protobuf:"bytes,25,opt,name=get_swarm_segment,json=getSwarmSegment,proto3,oneof"`
}

func (*Envelope_Handshake) isEnvelope_Body() {}

func (*Envelope_Ping) isEnvelope_Body() {}

func (*Envelope_Pong) isEnvelope_Body() {}

func (*Envelope_Browse) isEnvelope_Body() {}

func (*Envelope_Catalog) isEnvelope_Body() {}

func (*Envelope_GetMetadata) isEnvelope_Body() {}

func (*Envelope_TitleMeta) isEnvelope_Body() {}

func (*Envelope_RequestAccess) isEnvelope_Body() {}

func (*Envelope_AccessGranted) isEnvelope_Body() {}

func (*Envelope_Ack) isEnvelope_Body() {}

func (*Envelope_Error) isEnvelope_Body() {}

func (*Envelope_GetPlaylist) isEnvelope_Body() {}

func (*Envelope_Playlist_) isEnvelope_Body() {}

func (*Envelope_GetSegment) isEnvelope_Body() {}

func (*Envelope_Download) isEnvelope_Body() {}

func (*Envelope_JoinParty) isEnvelope_Body() {}

func (*Envelope_PartyWelcome) isEnvelope_Body() {}

func (*Envelope_PartyInvite) isEnvelope_Body() {}

func (*Envelope_PartyState) isEnvelope_Body() {}

func (*Envelope_PartyAudience) isEnvelope_Body() {}

func (*Envelope_LeaveParty) isEnvelope_Body() {}

func (*Envelope_PartyEnded) isEnvelope_Body() {}

func (*Envelope_SwarmHave) isEnvelope_Body() {}

func (*Envelope_GetSwarmSegment) isEnvelope_Body() {}

// Handshake is exchanged once when the control channel opens.
type Handshake struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Capabilities    []string               `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Handshake) Reset() {
	*x = Handshake{}
	mi := &file_proto_peer_v1_peer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handshake) ProtoMessage() {}

func (x *Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_v1_peer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handshake.ProtoReflect.Descriptor instead.
func (*Handshake) Descriptor() ([]byte, []int) {
	return file_proto_peer_v1_peer_proto_rawDescGZIP(), []int{1}
}

func (x *Handshake) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Handshake) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_proto_peer_v1_peer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_v1_peer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_proto_peer_v1_peer_proto_rawDescGZIP(), []int{2}
}

func (x *Ping) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_proto_peer_v1_peer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_v1_peer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_proto_peer_v1_peer_proto_rawDescGZIP(), []int{3}
}

func (x *Pong) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

type Browse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Browse) Reset() {
	*x = Browse{}
	mi := &file_proto_peer_v1_peer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Browse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Browse) ProtoMessage() {}

func (x *Browse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_v1_peer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Browse.ProtoReflect.Descriptor instead.
func (*Browse) Descriptor() ([]byte, []int) {
	return file_proto_peer_v1_peer_proto_rawDescGZIP(), []int{4}
}

type Catalog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Titles        []*TitleMeta           `protobuf:"bytes,1,rep,name=titles,proto3" json:"titles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Catalog) Reset() {
	*x = Catalog{}
	mi := &file_proto_peer_v1_peer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Catalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Catalog) ProtoMessage() {}

func (x *Catalog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_v1_peer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Catalog.ProtoReflect.Descriptor instead.
func (*Catalog) Descriptor() ([]byte, []int) {
	return file_proto_peer_v1_peer_proto_rawDescGZIP(), []int{5}
}

func (x *Catalog) GetTitles() []*TitleMeta {
	if x != nil {
		return x.Titles
	}
	return nil
}

type GetMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadata) Reset() {
	*x = GetMetadata{}
	mi := &file_proto_peer_v1_peer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadata) ProtoMessage() {}

func (x *GetMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_v1_peer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadata.ProtoReflect.Descriptor instead.
func (*GetMetadata) Descriptor() ([]byte, []int) {
	return file_proto_peer_v1_peer_proto_rawDescGZIP(), []int{6}
}

func (x *GetMetadata) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

type TitleMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	DisplayTitle  string                 `protobuf:"bytes,2,opt,name=display_title,json=displayTitle,proto3" json:"display_title,omitempty"`
	DurationMs    int64                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Container     string                 `protobuf:"bytes,4,opt,name=container,proto3" json:"container,omitempty"`
	VideoCodec    string                 `protobuf:"bytes,5,opt,name=video_codec,json=videoCodec,proto3" json:"video_codec,omitempty"`
	AudioCodecs   []string               `protobuf:"bytes,6,rep,name=audio_codecs,json=audioCodecs,proto3" json:"audio_codecs,omitempty"`
	Width         int32                  `protobuf:"varint,7,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,8,opt,name=height,proto3" json:"height,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,9,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	HlsCompatible bool                   `protobuf:"varint,10,opt,name=hls_compatible,json=hlsCompatible,proto3" json:"hls_compatible,omitempty"`
	Subtitles     []*SubtitleTrack       `protobuf:"bytes,11,rep,name=subtitles,proto3" json:"subtitles,omitempty"`
	PartyLive     bool                   `protobuf:"varint,12,opt,name=party_live,json=partyLive,proto3" json:"party_live,omitempty"`          // a live Watch Party exists for this Title on this Host
	PartyViewers  int32                  `protobuf:"varint,13,opt,name=party_viewers,json=partyViewers,proto3" json:"party_viewers,omitempty"` // current Audience size (Viewers, excluding the Host)
	Thumbnail     []byte                 `protobuf:"bytes,14,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`                            // small poster JPEG (480px); empty when unavailable
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TitleMeta) Reset() {
	*x = TitleMeta{}
	mi := &file_proto_peer_v1_peer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TitleMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TitleMeta) ProtoMessage() {}

func (x *TitleMeta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_v1_peer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TitleMeta.ProtoReflect.Descriptor instead.
func (*TitleMeta) Descriptor() ([]byte, []int) {
	return file_proto_peer_v1_peer_proto_rawDescGZIP(), []int{7}
}

func (x *TitleMeta) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *TitleMeta) GetDisplayTitle() string {
	if x != nil {
		return x.DisplayTitle
	}
	return ""
}

func (x *TitleMeta) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *TitleMeta) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *TitleMeta) GetVideoCodec() string {
	if x != nil {
		return x.VideoCodec
	}
	return ""
}

func (x *TitleMeta) GetAudioCodecs() []string {
	if x != nil {
		return x.AudioCodecs
	}
	return nil
}

func (x *TitleMeta) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *TitleMeta) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *TitleMeta) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *TitleMeta) GetHlsCompatible() bool {
	if x != nil {
		return x.HlsCompatible
	}
	return false
}

func (x *TitleMeta) GetSubtitles() []*SubtitleTrack {
	if x != nil {
		return x.Subtitles
	}
	return nil
}

func (x *TitleMeta) GetPartyLive() bool {
	if x != nil {
		return x.PartyLive
	}
	return false
}

func (x *TitleMeta) GetPartyViewers() int32 {
	if x != nil {
		return x.PartyViewers
	}
	return 0
}

func (x *TitleMeta) GetThumbnail() []byte {
	if x != nil {
		return x.Thumbnail
	}
	return nil
}

type SubtitleTrack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`             // "embedded:<index>" or "sidecar:<lang>"
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"` // ISO code or "und"
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Kind          string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"` // "text" | "image"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubtitleTrack) Reset() {
	*x = SubtitleTrack{}
	mi := &file_proto_peer_v1_peer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubtitleTrack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubtitleTrack) ProtoMessage() {}

func (x *SubtitleTrack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_v1_peer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubtitleTrack.ProtoReflect.Descriptor instead.
func (*SubtitleTrack) Descriptor() ([]byte, []int) {
	return file_proto_peer_v1_peer_proto_rawDescGZIP(), []int{8}
}

func (x *SubtitleTrack) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SubtitleTrack) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *SubtitleTrack) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SubtitleTrack) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type RequestAccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestAccess) Reset() {
	*x = RequestAccess{}
	mi := &file_proto_peer_v1_peer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAccess) ProtoMessage() {}

func (x *RequestAccess) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_v1_peer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAccess.ProtoReflect.Descriptor instead.
func (*RequestAccess) Descriptor() ([]byte, []int) {
	return file_proto_peer_v1_peer_proto_rawDescGZIP(), []int{9}
}

func (x *RequestAccess) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AccessGranted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessGranted) Reset() {
	*x = AccessGranted{}
	mi := &file_proto_peer_v1_peer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessGranted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessGranted) ProtoMessage() {}

func (x *AccessGranted) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_v1_peer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessGranted.ProtoReflect.Descriptor instead.
func (*AccessGranted) Descriptor() ([]byte, []int) {
	return file_proto_peer_v1_peer_proto_rawDescGZIP(), []int{10}
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_peer_v1_peer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_v1_peer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_peer_v1_peer_proto_rawDescGZIP(), []int{11}
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Error_Status           `protobuf:"varint,1,opt,name=status,proto3,enum=peer.v1.Error_Status" json:"status,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_proto_peer_v1_peer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_v1_peer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_peer_v1_peer_proto_rawDescGZIP(), []int{12}
}

func (x *Error) GetStatus() Error_Status {
	if x != nil {
		return x.Status
	}
	return Error_STATUS_UNSPECIFIED
}

func (x *Error) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// GetPlaylist requests a named playlist (e.g. "playlist.m3u8", "index.m3u8",
// "sub_eng.m3u8") for a Title. Small text response over the control channel.
type GetPlaylist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlaylist) Reset() {
	*x = GetPlaylist{}
	mi := &file_proto_peer_v1_peer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlaylist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlaylist) ProtoMessage() {}

func (x *GetPlaylist) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_v1_peer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlaylist.ProtoReflect.Descriptor instead.
func (*GetPlaylist) Descriptor() ([]byte, []int) {
	return file_proto_peer_v1_peer_proto_rawDescGZIP(), []int{13}
}

func (x *GetPlaylist) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *GetPlaylist) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Playlist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Complete      bool                   `protobuf:"varint,3,opt,name=complete,proto3" json:"complete,omitempty"` // false while ffmpeg is still producing (growing playlist)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Playlist) Reset() {
	*x = Playlist{}
	mi := &file_proto_peer_v1_peer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Playlist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Playlist) ProtoMessage() {}

func (x *Playlist) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_v1_peer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Playlist.ProtoReflect.Descriptor instead.
func (*Playlist) Descriptor() ([]byte, []int) {
	return file_proto_peer_v1_peer_proto_rawDescGZIP(), []int{14}
}

func (x *Playlist) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Playlist) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Playlist) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

// GetSegment requests a named segment ("seg00003.ts", "sub_eng_0.vtt").
// The bytes return on the bulk channel, correlated by request_id.
type GetSegment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSegment) Reset() {
	*x = GetSegment{}
	mi := &file_proto_peer_v1_peer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSegment) ProtoMessage() {}

func (x *GetSegment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_v1_peer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSegment.ProtoReflect.Descriptor instead.
func (*GetSegment) Descriptor() ([]byte, []int) {
	return file_proto_peer_v1_peer_proto_rawDescGZIP(), []int{15}
}

func (x *GetSegment) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *GetSegment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Download requests the original file bytes (streamed on the bulk channel).
type Download struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Download) Reset() {
	*x = Download{}
	mi := &file_proto_peer_v1_peer_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Download) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Download) ProtoMessage() {}

func (x *Download) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_v1_peer_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Download.ProtoReflect.Descriptor instead.
func (*Download) Descriptor() ([]byte, []int) {
	return file_proto_peer_v1_peer_proto_rawDescGZIP(), []int{16}
}

func (x *Download) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

// JoinParty asks a Host to admit this Viewer to the live Watch Party for a Title.
// content_id is only the join reference; the Host answers with the current party_id.
type JoinParty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinParty) Reset() {
	*x = JoinParty{}
	mi := &file_proto_peer_v1_peer_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinParty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinParty) ProtoMessage() {}

func (x *JoinParty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_v1_peer_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinParty.ProtoReflect.Descriptor instead.
func (*JoinParty) Descriptor() ([]byte, []int) {
	return file_proto_peer_v1_peer_proto_rawDescGZIP(), []int{17}
}

func (x *JoinParty) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

// PartyWelcome admits a Viewer: the assigned party_id, the current authoritative
// state, and the current Audience.
type PartyWelcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartyId       string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	Initial       *PartyState            `protobuf:"bytes,2,opt,name=initial,proto3" json:"initial,omitempty"`
	Audience      *PartyAudience         `protobuf:"bytes,3,opt,name=audience,proto3" json:"audience,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyWelcome) Reset() {
	*x = PartyWelcome{}
	mi := &file_proto_peer_v1_peer_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyWelcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyWelcome) ProtoMessage() {}

func (x *PartyWelcome) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_v1_peer_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyWelcome.ProtoReflect.Descriptor instead.
func (*PartyWelcome) Descriptor() ([]byte, []int) {
	return file_proto_peer_v1_peer_proto_rawDescGZIP(), []int{18}
}

func (x *PartyWelcome) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *PartyWelcome) GetInitial() *PartyState {
	if x != nil {
		return x.Initial
	}
	return nil
}

func (x *PartyWelcome) GetAudience() *PartyAudience {
	if x != nil {
		return x.Audience
	}
	return nil
}

// PartyInvite is pushed by a Host to proactively invite a Node to a Watch Party.
type PartyInvite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	PartyId       string                 `protobuf:"bytes,2,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	HostDisplay   string                 `protobuf:"bytes,3,opt,name=host_display,json=hostDisplay,proto3" json:"host_display,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyInvite) Reset() {
	*x = PartyInvite{}
	mi := &file_proto_peer_v1_peer_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyInvite) ProtoMessage() {}

func (x *PartyInvite) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_v1_peer_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyInvite.ProtoReflect.Descriptor instead.
func (*PartyInvite) Descriptor() ([]byte, []int) {
	return file_proto_peer_v1_peer_proto_rawDescGZIP(), []int{19}
}

func (x *PartyInvite) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *PartyInvite) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *PartyInvite) GetHostDisplay() string {
	if x != nil {
		return x.HostDisplay
	}
	return ""
}

// PartyState is the Host's authoritative playback state at a sample instant.
// It is both the periodic heartbeat and the on-change event (highest seq wins).
type PartyState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartyId       string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	Playing       bool                   `protobuf:"varint,2,opt,name=playing,proto3" json:"playing,omitempty"`
	PositionMs    int64                  `protobuf:"varint,3,opt,name=position_ms,json=positionMs,proto3" json:"position_ms,omitempty"`
	HostClockMs   int64                  `protobuf:"varint,4,opt,name=host_clock_ms,json=hostClockMs,proto3" json:"host_clock_ms,omitempty"` // reserved for the NTP fallback; unused by the RTT/2 model
	Rate          float64                `protobuf:"fixed64,5,opt,name=rate,proto3" json:"rate,omitempty"`
	Seq           uint64                 `protobuf:"varint,6,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyState) Reset() {
	*x = PartyState{}
	mi := &file_proto_peer_v1_peer_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyState) ProtoMessage() {}

func (x *PartyState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_v1_peer_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyState.ProtoReflect.Descriptor instead.
func (*PartyState) Descriptor() ([]byte, []int) {
	return file_proto_peer_v1_peer_proto_rawDescGZIP(), []int{20}
}

func (x *PartyState) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *PartyState) GetPlaying() bool {
	if x != nil {
		return x.Playing
	}
	return false
}

func (x *PartyState) GetPositionMs() int64 {
	if x != nil {
		return x.PositionMs
	}
	return 0
}

func (x *PartyState) GetHostClockMs() int64 {
	if x != nil {
		return x.HostClockMs
	}
	return 0
}

func (x *PartyState) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *PartyState) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

// PartyAudience is the current set of Viewers in a Watch Party.
type PartyAudience struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartyId       string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	Members       []*AudienceMember      `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyAudience) Reset() {
	*x = PartyAudience{}
	mi := &file_proto_peer_v1_peer_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyAudience) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyAudience) ProtoMessage() {}

func (x *PartyAudience) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_v1_peer_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyAudience.ProtoReflect.Descriptor instead.
func (*PartyAudience) Descriptor() ([]byte, []int) {
	return file_proto_peer_v1_peer_proto_rawDescGZIP(), []int{21}
}

func (x *PartyAudience) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *PartyAudience) GetMembers() []*AudienceMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type AudienceMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudienceMember) Reset() {
	*x = AudienceMember{}
	mi := &file_proto_peer_v1_peer_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudienceMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudienceMember) ProtoMessage() {}

func (x *AudienceMember) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_v1_peer_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudienceMember.ProtoReflect.Descriptor instead.
func (*AudienceMember) Descriptor() ([]byte, []int) {
	return file_proto_peer_v1_peer_proto_rawDescGZIP(), []int{22}
}

func (x *AudienceMember) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AudienceMember) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

// LeaveParty tells the Host this Viewer is leaving the Audience.
type LeaveParty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartyId       string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveParty) Reset() {
	*x = LeaveParty{}
	mi := &file_proto_peer_v1_peer_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveParty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveParty) ProtoMessage() {}

func (x *LeaveParty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_v1_peer_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveParty.ProtoReflect.Descriptor instead.
func (*LeaveParty) Descriptor() ([]byte, []int) {
	return file_proto_peer_v1_peer_proto_rawDescGZIP(), []int{23}
}

func (x *LeaveParty) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

// PartyEnded tells Viewers the Host has stopped the Watch Party.
type PartyEnded struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartyId       string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyEnded) Reset() {
	*x = PartyEnded{}
	mi := &file_proto_peer_v1_peer_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyEnded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyEnded) ProtoMessage() {}

func (x *PartyEnded) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_v1_peer_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyEnded.ProtoReflect.Descriptor instead.
func (*PartyEnded) Descriptor() ([]byte, []int) {
	return file_proto_peer_v1_peer_proto_rawDescGZIP(), []int{24}
}

func (x *PartyEnded) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *PartyEnded) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// SwarmHave is the gossip have-map: the windowed set of Segments the sender holds
// for a party, as base_index + bitmap (bit i set => has Segment base_index+i).
type SwarmHave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartyId       string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	Rendition     string                 `protobuf:"bytes,2,opt,name=rendition,proto3" json:"rendition,omitempty"`
	BaseIndex     uint32                 `protobuf:"varint,3,opt,name=base_index,json=baseIndex,proto3" json:"base_index,omitempty"`
	Bitmap        []byte                 `protobuf:"bytes,4,opt,name=bitmap,proto3" json:"bitmap,omitempty"`
	Epoch         uint64                 `protobuf:"varint,5,opt,name=epoch,proto3" json:"epoch,omitempty"` // monotonic; receivers ignore lower-or-equal epochs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwarmHave) Reset() {
	*x = SwarmHave{}
	mi := &file_proto_peer_v1_peer_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwarmHave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwarmHave) ProtoMessage() {}

func (x *SwarmHave) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_v1_peer_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwarmHave.ProtoReflect.Descriptor instead.
func (*SwarmHave) Descriptor() ([]byte, []int) {
	return file_proto_peer_v1_peer_proto_rawDescGZIP(), []int{25}
}

func (x *SwarmHave) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *SwarmHave) GetRendition() string {
	if x != nil {
		return x.Rendition
	}
	return ""
}

func (x *SwarmHave) GetBaseIndex() uint32 {
	if x != nil {
		return x.BaseIndex
	}
	return 0
}

func (x *SwarmHave) GetBitmap() []byte {
	if x != nil {
		return x.Bitmap
	}
	return nil
}

func (x *SwarmHave) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

// GetSwarmSegment requests a cached Segment from a peer Viewer in the same party.
// The bytes return on the bulk channel, correlated by request_id (like GetSegment).
type GetSwarmSegment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartyId       string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	Rendition     string                 `protobuf:"bytes,2,opt,name=rendition,proto3" json:"rendition,omitempty"`
	SegName       string                 `protobuf:"bytes,3,opt,name=seg_name,json=segName,proto3" json:"seg_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSwarmSegment) Reset() {
	*x = GetSwarmSegment{}
	mi := &file_proto_peer_v1_peer_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSwarmSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSwarmSegment) ProtoMessage() {}

func (x *GetSwarmSegment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_v1_peer_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSwarmSegment.ProtoReflect.Descriptor instead.
func (*GetSwarmSegment) Descriptor() ([]byte, []int) {
	return file_proto_peer_v1_peer_proto_rawDescGZIP(), []int{26}
}

func (x *GetSwarmSegment) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *GetSwarmSegment) GetRendition() string {
	if x != nil {
		return x.Rendition
	}
	return ""
}

func (x *GetSwarmSegment) GetSegName() string {
	if x != nil {
		return x.SegName
	}
	return ""
}

var File_proto_peer_v1_peer_proto protoreflect.FileDescriptor

const file_proto_peer_v1_peer_proto_rawDesc = "" +
	"\n" +
	"\x18proto/peer/v1/peer.proto\x12\apeer.v1\"\xad\n" +
	"\n" +
	"\bEnvelope\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x122\n" +
	"\thandshake\x18\x02 \x01(\v2\x12.peer.v1.HandshakeH\x00R\thandshake\x12#\n" +
	"\x04ping\x18\x03 \x01(\v2\r.peer.v1.PingH\x00R\x04ping\x12#\n" +
	"\x04pong\x18\x04 \x01(\v2\r.peer.v1.PongH\x00R\x04pong\x12)\n" +
	"\x06browse\x18\x05 \x01(\v2\x0f.peer.v1.BrowseH\x00R\x06browse\x12,\n" +
	"\acatalog\x18\x06 \x01(\v2\x10.peer.v1.CatalogH\x00R\acatalog\x129\n" +
	"\fget_metadata\x18\a \x01(\v2\x14.peer.v1.GetMetadataH\x00R\vgetMetadata\x123\n" +
	"\n" +
	"title_meta\x18\b \x01(\v2\x12.peer.v1.TitleMetaH\x00R\ttitleMeta\x12?\n" +
	"\x0erequest_access\x18\t \x01(\v2\x16.peer.v1.RequestAccessH\x00R\rrequestAccess\x12?\n" +
	"\x0eaccess_granted\x18\n" +
	" \x01(\v2\x16.peer.v1.AccessGrantedH\x00R\raccessGranted\x12 \n" +
	"\x03ack\x18\v \x01(\v2\f.peer.v1.AckH\x00R\x03ack\x12&\n" +
	"\x05error\x18\f \x01(\v2\x0e.peer.v1.ErrorH\x00R\x05error\x129\n" +
	"\fget_playlist\x18\r \x01(\v2\x14.peer.v1.GetPlaylistH\x00R\vgetPlaylist\x12/\n" +
	"\bplaylist\x18\x0e \x01(\v2\x11.peer.v1.PlaylistH\x00R\bplaylist\x126\n" +
	"\vget_segment\x18\x0f \x01(\v2\x13.peer.v1.GetSegmentH\x00R\n" +
	"getSegment\x12/\n" +
	"\bdownload\x18\x10 \x01(\v2\x11.peer.v1.DownloadH\x00R\bdownload\x123\n" +
	"\n" +
	"join_party\x18\x11 \x01(\v2\x12.peer.v1.JoinPartyH\x00R\tjoinParty\x12<\n" +
	"\rparty_welcome\x18\x12 \x01(\v2\x15.peer.v1.PartyWelcomeH\x00R\fpartyWelcome\x129\n" +
	"\fparty_invite\x18\x13 \x01(\v2\x14.peer.v1.PartyInviteH\x00R\vpartyInvite\x126\n" +
	"\vparty_state\x18\x14 \x01(\v2\x13.peer.v1.PartyStateH\x00R\n" +
	"partyState\x12?\n" +
	"\x0eparty_audience\x18\x15 \x01(\v2\x16.peer.v1.PartyAudienceH\x00R\rpartyAudience\x126\n" +
	"\vleave_party\x18\x16 \x01(\v2\x13.peer.v1.LeavePartyH\x00R\n" +
	"leaveParty\x126\n" +
	"\vparty_ended\x18\x17 \x01(\v2\x13.peer.v1.PartyEndedH\x00R\n" +
	"partyEnded\x123\n" +
	"\n" +
	"swarm_have\x18\x18 \x01(\v2\x12.peer.v1.SwarmHaveH\x00R\tswarmHave\x12F\n" +
	"\x11get_swarm_segment\x18\x19 \x01(\v2\x18.peer.v1.GetSwarmSegmentH\x00R\x0fgetSwarmSegmentB\x06\n" +
	"\x04body\"Z\n" +
	"\tHandshake\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\"\x1c\n" +
	"\x04Ping\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce\"\x1c\n" +
	"\x04Pong\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce\"\b\n" +
	"\x06Browse\"5\n" +
	"\aCatalog\x12*\n" +
	"\x06titles\x18\x01 \x03(\v2\x12.peer.v1.TitleMetaR\x06titles\",\n" +
	"\vGetMetadata\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\"\xde\x03\n" +
	"\tTitleMeta\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12#\n" +
	"\rdisplay_title\x18\x02 \x01(\tR\fdisplayTitle\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x03R\n" +
	"durationMs\x12\x1c\n" +
	"\tcontainer\x18\x04 \x01(\tR\tcontainer\x12\x1f\n" +
	"\vvideo_codec\x18\x05 \x01(\tR\n" +
	"videoCodec\x12!\n" +
	"\faudio_codecs\x18\x06 \x03(\tR\vaudioCodecs\x12\x14\n" +
	"\x05width\x18\a \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\b \x01(\x05R\x06height\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\t \x01(\x03R\tsizeBytes\x12%\n" +
	"\x0ehls_compatible\x18\n" +
	" \x01(\bR\rhlsCompatible\x124\n" +
	"\tsubtitles\x18\v \x03(\v2\x16.peer.v1.SubtitleTrackR\tsubtitles\x12\x1d\n" +
	"\n" +
	"party_live\x18\f \x01(\bR\tpartyLive\x12#\n" +
	"\rparty_viewers\x18\r \x01(\x05R\fpartyViewers\x12\x1c\n" +
	"\tthumbnail\x18\x0e \x01(\fR\tthumbnail\"e\n" +
	"\rSubtitleTrack\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\")\n" +
	"\rRequestAccess\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x0f\n" +
	"\rAccessGranted\"\x05\n" +
	"\x03Ack\"\xb4\x01\n" +
	"\x05Error\x12-\n" +
	"\x06status\x18\x01 \x01(\x0e2\x15.peer.v1.Error.StatusR\x06status\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"d\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06DENIED\x10\x01\x12\r\n" +
	"\tNOT_FOUND\x10\x02\x12\x0f\n" +
	"\vUNAVAILABLE\x10\x03\x12\f\n" +
	"\bINTERNAL\x10\x04\x12\b\n" +
	"\x04BUSY\x10\x05\"@\n" +
	"\vGetPlaylist\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"]\n" +
	"\bPlaylist\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x1a\n" +
	"\bcomplete\x18\x03 \x01(\bR\bcomplete\"?\n" +
	"\n" +
	"GetSegment\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\")\n" +
	"\bDownload\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\"*\n" +
	"\tJoinParty\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\"\x8c\x01\n" +
	"\fPartyWelcome\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12-\n" +
	"\ainitial\x18\x02 \x01(\v2\x13.peer.v1.PartyStateR\ainitial\x122\n" +
	"\baudience\x18\x03 \x01(\v2\x16.peer.v1.PartyAudienceR\baudience\"j\n" +
	"\vPartyInvite\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12\x19\n" +
	"\bparty_id\x18\x02 \x01(\tR\apartyId\x12!\n" +
	"\fhost_display\x18\x03 \x01(\tR\vhostDisplay\"\xac\x01\n" +
	"\n" +
	"PartyState\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12\x18\n" +
	"\aplaying\x18\x02 \x01(\bR\aplaying\x12\x1f\n" +
	"\vposition_ms\x18\x03 \x01(\x03R\n" +
	"positionMs\x12\"\n" +
	"\rhost_clock_ms\x18\x04 \x01(\x03R\vhostClockMs\x12\x12\n" +
	"\x04rate\x18\x05 \x01(\x01R\x04rate\x12\x10\n" +
	"\x03seq\x18\x06 \x01(\x04R\x03seq\"]\n" +
	"\rPartyAudience\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x121\n" +
	"\amembers\x18\x02 \x03(\v2\x17.peer.v1.AudienceMemberR\amembers\"L\n" +
	"\x0eAudienceMember\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\"'\n" +
	"\n" +
	"LeaveParty\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\"?\n" +
	"\n" +
	"PartyEnded\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x91\x01\n" +
	"\tSwarmHave\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12\x1c\n" +
	"\trendition\x18\x02 \x01(\tR\trendition\x12\x1d\n" +
	"\n" +
	"base_index\x18\x03 \x01(\rR\tbaseIndex\x12\x16\n" +
	"\x06bitmap\x18\x04 \x01(\fR\x06bitmap\x12\x14\n" +
	"\x05epoch\x18\x05 \x01(\x04R\x05epoch\"e\n" +
	"\x0fGetSwarmSegment\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12\x1c\n" +
	"\trendition\x18\x02 \x01(\tR\trendition\x12\x19\n" +
	"\bseg_name\x18\x03 \x01(\tR\asegNameB5Z3github.com/squall-chua/p2p-hls/proto/peer/v1;peerv1b\x06proto3"

var (
	file_proto_peer_v1_peer_proto_rawDescOnce sync.Once
	file_proto_peer_v1_peer_proto_rawDescData []byte
)

func file_proto_peer_v1_peer_proto_rawDescGZIP() []byte {
	file_proto_peer_v1_peer_proto_rawDescOnce.Do(func() {
		file_proto_peer_v1_peer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_peer_v1_peer_proto_rawDesc), len(file_proto_peer_v1_peer_proto_rawDesc)))
	})
	return file_proto_peer_v1_peer_proto_rawDescData
}

var file_proto_peer_v1_peer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_peer_v1_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_proto_peer_v1_peer_proto_goTypes = []any{
	(Error_Status)(0),       // 0: peer.v1.Error.Status
	(*Envelope)(nil),        // 1: peer.v1.Envelope
	(*Handshake)(nil),       // 2: peer.v1.Handshake
	(*Ping)(nil),            // 3: peer.v1.Ping
	(*Pong)(nil),            // 4: peer.v1.Pong
	(*Browse)(nil),          // 5: peer.v1.Browse
	(*Catalog)(nil),         // 6: peer.v1.Catalog
	(*GetMetadata)(nil),     // 7: peer.v1.GetMetadata
	(*TitleMeta)(nil),       // 8: peer.v1.TitleMeta
	(*SubtitleTrack)(nil),   // 9: peer.v1.SubtitleTrack
	(*RequestAccess)(nil),   // 10: peer.v1.RequestAccess
	(*AccessGranted)(nil),   // 11: peer.v1.AccessGranted
	(*Ack)(nil),             // 12: peer.v1.Ack
	(*Error)(nil),           // 13: peer.v1.Error
	(*GetPlaylist)(nil),     // 14: peer.v1.GetPlaylist
	(*Playlist)(nil),        // 15: peer.v1.Playlist
	(*GetSegment)(nil),      // 16: peer.v1.GetSegment
	(*Download)(nil),        // 17: peer.v1.Download
	(*JoinParty)(nil),       // 18: peer.v1.JoinParty
	(*PartyWelcome)(nil),    // 19: peer.v1.PartyWelcome
	(*PartyInvite)(nil),     // 20: peer.v1.PartyInvite
	(*PartyState)(nil),      // 21: peer.v1.PartyState
	(*PartyAudience)(nil),   // 22: peer.v1.PartyAudience
	(*AudienceMember)(nil),  // 23: peer.v1.AudienceMember
	(*LeaveParty)(nil),      // 24: peer.v1.LeaveParty
	(*PartyEnded)(nil),      // 25: peer.v1.PartyEnded
	(*SwarmHave)(nil),       // 26: peer.v1.SwarmHave
	(*GetSwarmSegment)(nil), // 27: peer.v1.GetSwarmSegment
}
var file_proto_peer_v1_peer_proto_depIdxs = []int32{
	2,  // 0: peer.v1.Envelope.handshake:type_name -> peer.v1.Handshake
	3,  // 1: peer.v1.Envelope.ping:type_name -> peer.v1.Ping
	4,  // 2: peer.v1.Envelope.pong:type_name -> peer.v1.Pong
	5,  // 3: peer.v1.Envelope.browse:type_name -> peer.v1.Browse
	6,  // 4: peer.v1.Envelope.catalog:type_name -> peer.v1.Catalog
	7,  // 5: peer.v1.Envelope.get_metadata:type_name -> peer.v1.GetMetadata
	8,  // 6: peer.v1.Envelope.title_meta:type_name -> peer.v1.TitleMeta
	10, // 7: peer.v1.Envelope.request_access:type_name -> peer.v1.RequestAccess
	11, // 8: peer.v1.Envelope.access_granted:type_name -> peer.v1.AccessGranted
	12, // 9: peer.v1.Envelope.ack:type_name -> peer.v1.Ack
	13, // 10: peer.v1.Envelope.error:type_name -> peer.v1.Error
	14, // 11: peer.v1.Envelope.get_playlist:type_name -> peer.v1.GetPlaylist
	15, // 12: peer.v1.Envelope.playlist:type_name -> peer.v1.Playlist
	16, // 13: peer.v1.Envelope.get_segment:type_name -> peer.v1.GetSegment
	17, // 14: peer.v1.Envelope.download:type_name -> peer.v1.Download
	18, // 15: peer.v1.Envelope.join_party:type_name -> peer.v1.JoinParty
	19, // 16: peer.v1.Envelope.party_welcome:type_name -> peer.v1.PartyWelcome
	20, // 17: peer.v1.Envelope.party_invite:type_name -> peer.v1.PartyInvite
	21, // 18: peer.v1.Envelope.party_state:type_name -> peer.v1.PartyState
	22, // 19: peer.v1.Envelope.party_audience:type_name -> peer.v1.PartyAudience
	24, // 20: peer.v1.Envelope.leave_party:type_name -> peer.v1.LeaveParty
	25, // 21: peer.v1.Envelope.party_ended:type_name -> peer.v1.PartyEnded
	26, // 22: peer.v1.Envelope.swarm_have:type_name -> peer.v1.SwarmHave
	27, // 23: peer.v1.Envelope.get_swarm_segment:type_name -> peer.v1.GetSwarmSegment
	8,  // 24: peer.v1.Catalog.titles:type_name -> peer.v1.TitleMeta
	9,  // 25: peer.v1.TitleMeta.subtitles:type_name -> peer.v1.SubtitleTrack
	0,  // 26: peer.v1.Error.status:type_name -> peer.v1.Error.Status
	21, // 27: peer.v1.PartyWelcome.initial:type_name -> peer.v1.PartyState
	22, // 28: peer.v1.PartyWelcome.audience:type_name -> peer.v1.PartyAudience
	23, // 29: peer.v1.PartyAudience.members:type_name -> peer.v1.AudienceMember
	30, // [30:30] is the sub-list for method output_type
	30, // [30:30] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_proto_peer_v1_peer_proto_init() }
func file_proto_peer_v1_peer_proto_init() {
	if File_proto_peer_v1_peer_proto != nil {
		return
	}
	file_proto_peer_v1_peer_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Handshake)(nil),
		(*Envelope_Ping)(nil),
		(*Envelope_Pong)(nil),
		(*Envelope_Browse)(nil),
		(*Envelope_Catalog)(nil),
		(*Envelope_GetMetadata)(nil),
		(*Envelope_TitleMeta)(nil),
		(*Envelope_RequestAccess)(nil),
		(*Envelope_AccessGranted)(nil),
		(*Envelope_Ack)(nil),
		(*Envelope_Error)(nil),
		(*Envelope_GetPlaylist)(nil),
		(*Envelope_Playlist_)(nil),
		(*Envelope_GetSegment)(nil),
		(*Envelope_Download)(nil),
		(*Envelope_JoinParty)(nil),
		(*Envelope_PartyWelcome)(nil),
		(*Envelope_PartyInvite)(nil),
		(*Envelope_PartyState)(nil),
		(*Envelope_PartyAudience)(nil),
		(*Envelope_LeaveParty)(nil),
		(*Envelope_PartyEnded)(nil),
		(*Envelope_SwarmHave)(nil),
		(*Envelope_GetSwarmSegment)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_peer_v1_peer_proto_rawDesc), len(file_proto_peer_v1_peer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_peer_v1_peer_proto_goTypes,
		DependencyIndexes: file_proto_peer_v1_peer_proto_depIdxs,
		EnumInfos:         file_proto_peer_v1_peer_proto_enumTypes,
		MessageInfos:      file_proto_peer_v1_peer_proto_msgTypes,
	}.Build()
	File_proto_peer_v1_peer_proto = out.File
	file_proto_peer_v1_peer_proto_goTypes = nil
	file_proto_peer_v1_peer_proto_depIdxs = nil
}
